name: example
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"
description: Example app for KISS Repository
dependencies:
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  kiss_dependencies: ^1.3.0
  kiss_firebase_repository: ^0.9.0
  kiss_pocketbase_repository: ^0.1.0
  kiss_repository: ^0.11.0
  meta: ^1.11.0
  pocketbase: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pubspec_dependency_sorter: ^1.0.5
  very_good_analysis: ^6.0.0
flutter:
  uses-material-design: true
