name: kiss_repository
description: A simple generic repository interface
version: 0.8.1
repository: https://github.com/WAMF/kiss_repository

environment:
  sdk: ^3.6.0

dependencies:
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.20.0
