name: kiss_repository
description: A simple generic repository interface
version: 0.16.0
repository: https://github.com/WAMF/kiss_repository

environment:
  sdk: ^3.6.0

dependencies:
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^6.0.0
